image: node:7.1.0
pipelines:
  default:
    - step:
        script:
          - echo "This script runs on all branches that don't have any specific pipeline assigned in 'branches'."
          # Install app requirements
          - npm install
          # Testing app
          - npm test          
  branches:
    master:
      - step:
          script:
            - echo "This script runs only on commit to the master branch."            
            # Install app requirements
            # - npm install
            # Testing app
            # - npm test            
            # Configuration new version
            - chmod +x deploy/new_version.sh
            - ./deploy/new_version.sh
            - export VERSION=$(cat deploy/VERSION)
            - export VERSION_UNDERSCORE=$(cat deploy/VERSION_UNDERSCORE)
            - git config --global user.email "development@domoti.rocks"
            - git config --global user.name "DOMOTI S.A.S."
            - git add deploy/VERSION
            - git commit -am "Update to new version ${VERSION}"
            - echo $VERSION_UNDERSCORE
            # Install Google Cloud SDK is pinned for build reliability. Bump if the SDK complains about deprecation.
            - export CLOUDSDK_CORE_PROJECT=$(cat deploy/gcp/CLOUDSDK_CORE_PROJECT)
            - SDK_VERSION=138.0.0
            - SDK_FILENAME=google-cloud-sdk-${SDK_VERSION}-linux-x86_64.tar.gz
            - curl -O -J https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/${SDK_FILENAME}
            - tar -zxvf ${SDK_FILENAME} --directory ${HOME}
            - export PATH=${PATH}:${HOME}/google-cloud-sdk/bin          
            # Configure Google Cloud SDK
            - gcloud auth activate-service-account --key-file deploy/gcp/GOOGLE_CLIENT_SECRET.json      
            # Finish deploy (--log-http --verbosity=debug) 
            - gcloud config set project ${CLOUDSDK_CORE_PROJECT}        
            - gcloud --quiet --verbosity=error app deploy app.yaml --promote --stop-previous-version -v ${VERSION_UNDERSCORE}            
            - ./deploy/slack/slack.sh
    feature/*:
      - step:
          image: java:openjdk-9 # This step uses its own image
          script:
            - echo "This script runs only on commit to branches with names that match the feature/* pattern."