image: node:5.11.0
pipelines:
  default:
    - step:
        script:
          - echo "This script runs on all branches that don't have any specific pipeline assigned in 'branches'."
  branches:
    master:
      - step:
          script:
            - echo "This script runs only on commit to the master branch."
            - echo "This script runs only on commit to the master branch."
            # Configuration new version
            - export VERSION=$(cat deploy/VERSION)
            - ARRAY_VERSION=(${VERSION//./ })
            - VERSION_MAJOR=${ARRAY_VERSION[0]}
            - VERSION_MINOR=${ARRAY_VERSION[1]}
            - VERSION_CONSECUTIVE=${ARRAY_VERSION[2]}
            - VERSION_NEW_CONSECUTIVE=VERSION_CONSECUTIVE
            - VERSION_NEW_MINOR=VERSION_MINOR
            - let VERSION_NEW_CONSECUTIVE+=1                        
            - echo "Se subirá de version ${VERSION} a ${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_NEW_CONSECUTIVE}"
            - echo ${VERSION_MAJOR}.${VERSION_NEW_MINOR}.${VERSION_NEW_CONSECUTIVE} > deploy/VERSION
            - git add deploy/VERSION
            - git commit -am "Update to new version ${VERSION_MAJOR}.${VERSION_NEW_MINOR}.${VERSION_NEW_CONSECUTIVE}"
            - git push
            # Finish deploy (--log-http --verbosity=debug) 
            - export URL_DEPLOY=https://${VERSION_MAJOR}-${VERSION_MINOR}-${VERSION_NEW_CONSECUTIVE}-dot-${CLOUDSDK_CORE_PROJECT}.appspot-preview.com
            - echo "curl -X POST --data-urlencode 'payload={\"channel\": \"#${SLACK_CHANNEL}\", \"username\": \"DOMOTI\", \"text\": \"Se ha desplegado una nueva version de ${BRANCH} en ${URL_DEPLOY}\"}' ${SLACK_WEBHOOKS}" > slack.sh
            - chmod +x slack.sh && ./slack.sh  
    feature/*:
      - step:
          image: java:openjdk-9 # This step uses its own image
          script:
            - echo "This script runs only on commit to branches with names that match the feature/* pattern."