image: node:5.11.0
pipelines:
  default:
    - step:
        script:
          - echo "This script runs on all branches that don't have any specific pipeline assigned in 'branches'."
  branches:
    master:
      - step:
          script:
            - echo "This script runs only on commit to the master branch."            
            # Configuration new version
            - chmod +x deploy/new_version.sh
            - ./deploy/new_version.sh
            - export VERSION=$(cat deploy/VERSION)
            - export VERSION_UNDERSCORE=$(cat deploy/VERSION_UNDERSCORE)
            - git add deploy/VERSION
            - git commit -am "Update to new version ${VERSION}"
            - git push
            # Finish deploy (--log-http --verbosity=debug) 
            - ./deploy/slack/slack.sh
    feature/*:
      - step:
          image: java:openjdk-9 # This step uses its own image
          script:
            - echo "This script runs only on commit to branches with names that match the feature/* pattern."