module.exports = {
	MOTIVES: {
		'EVALUATOR': {
			'ACEPTAR_REQUISITO': 1,
			'CALIFICAR_REQUISITO': 2,
			'VER_VIDEO': 3,
			'POSTULARSE_EVALUAR': 4,
			'EVENTOS': 5,
			'NO_EVALUAR': 6,
			'RECHAZAR': 7
		},
		'ENTITY': {
			'VER_VIDEO': 3,
			'EVENTOS': 5,
			'PASAR_REQUISITO_NIVEL_1': 8,
			'PASAR_REQUISITO_NIVEL_2': 9,
			'PASAR_REQUISITO_NIVEL_3': 10,
			'PERDER_REQUISITO': 11,
		}
	},
	SERVICE: {
		'VERIFICACION': 1,
		'ASIGNACION': 2,
		'ACEPTACION': 3,
		'RETIRADO': 4,
		'EVALUACION': 5,
		'RETROALIMENTACION': 6,
		'CIERRE': 7,
		'CUMPLE': 8,
		'NO_CUMPLE': 9,
		'INCOMPLETO': 10,
		'RECHAZADO': 11
	},
	EVALUATION_REQUEST: {
		'PENDIENTE': 1,
		'SOLICITADO': 2,
		'ASIGNADO': 3,
		'ACEPTADO': 4,
		'RECHAZADO': 5,
		'RETROALIMENTACION': 6,
		'CUMPLE': 7,
		'NO_CUMPLE': 8
	}
}