/**  * MODEL AUTO_GENERATED BY DMT-GENERATOR
 * category_questions
 * [{"Field":"id","Type":"int(11)","Null":"NO","Key":"PRI","Default":null,"Extra":"auto_increment"},{"Field":"id_category","Type":"int(11)","Null":"YES","Key":"MUL","Default":null,"Extra":""},{"Field":"text","Type":"varchar(255)","Null":"YES","Key":"","Default":null,"Extra":""}]
 * DMT 2017
 * GENERATED: 18 / 8 / 2017 - 13:23:2
 **/
var BaseModel = require('../utils/model.js')
var util = require('util')
var Category_questions = function () {
	var params = [{
		table:'category_questions',
		fields :[{"Field":"id","Type":"int(11)","Null":"NO","Key":"PRI","Default":null,"Extra":"auto_increment"},{"Field":"id_category","Type":"int(11)","Null":"YES","Key":"MUL","Default":null,"Extra":""},{"Field":"text","Type":"varchar(255)","Null":"YES","Key":"","Default":null,"Extra":""}],
		model:'mysql'
	}]
	BaseModel.apply(this, params)
	return this
};
util.inherits(Category_questions, BaseModel)
module.exports = Category_questions