/**  * MODEL AUTO_GENERATED BY DMT-GENERATOR
 * category
 * [{"Field":"id","Type":"int(11)","Null":"NO","Key":"PRI","Default":null,"Extra":"auto_increment"},{"Field":"name","Type":"varchar(50)","Null":"YES","Key":"","Default":null,"Extra":""}]
 * DMT 2017
 * GENERATED: 5 / 9 / 2017 - 7:38:21
 **/
var BaseModel = require('../utils/model.js')
var util = require('util')
var Category = function () {
	var params = [{
		table:'category',
		fields :[
			{"Field":"id","Type":"int(11)","Null":"NO","Key":"PRI","Default":null,"Extra":"auto_increment"},
			{"Field":"name","Type":"varchar(50)","Null":"YES","Key":"","Default":null,"Extra":""},
			{"Field":"diploma","Type":"int(11)","Null":"YES","Key":"","Default":null,"Extra":""}],
		model:'mysql'
	}]
	BaseModel.apply(this, params)
	return this
};
util.inherits(Category, BaseModel)
module.exports = Category