/**  * MODEL AUTO_GENERATED BY DMT-GENERATOR
 * ciudades
 * [{"Field":"id_region","Type":"int(11)","Null":"YES","Key":"","Default":null,"Extra":""},{"Field":"name","Type":"text","Null":"YES","Key":"","Default":null,"Extra":""}]
 * DMT 2017
 * GENERATED: 22 / 8 / 2017 - 9:41:42
 **/
var BaseModel = require('../utils/model.js')
var util = require('util')
var Ciudades = function () {
	var params = [{
		table:'ciudades',
		fields :[{"Field":"id_region","Type":"int(11)","Null":"YES","Key":"","Default":null,"Extra":""},{"Field":"name","Type":"text","Null":"YES","Key":"","Default":null,"Extra":""}],
		model:'mysql'
	}]
	BaseModel.apply(this, params)
	return this
};
util.inherits(Ciudades, BaseModel)
module.exports = Ciudades