/**  * MODEL AUTO_GENERATED BY DMT-GENERATOR
 * config
 * [{"Field":"id","Type":"int(11)","Null":"NO","Key":"PRI","Default":null,"Extra":"auto_increment"},{"Field":"key","Type":"varchar(255)","Null":"YES","Key":"","Default":null,"Extra":""},{"Field":"value","Type":"varchar(255)","Null":"YES","Key":"","Default":null,"Extra":""}]
 * DMT 2017
 * GENERATED: 4 / 2 / 2017 - 23:15:0
 **/
var BaseModel = require('../utils/model.js')
var util = require('util')
var Config = function () {
	this.fields = [{"Field":"id","Type":"int(11)","Null":"NO","Key":"PRI","Default":null,"Extra":"auto_increment"},{"Field":"key","Type":"varchar(255)","Null":"YES","Key":"","Default":null,"Extra":""},{"Field":"value","Type":"varchar(255)","Null":"YES","Key":"","Default":null,"Extra":""}]
	var params = ['config', 'mysql']
	BaseModel.apply(this, params)
	return this
};
util.inherits(Config, BaseModel)
module.exports = Config