/**  * MODEL AUTO_GENERATED BY DMT-GENERATOR
 * form_question
 * [{"Field":"id_form","Type":"int(11)","Null":"YES","Key":"MUL","Default":null,"Extra":""},{"Field":"id_question","Type":"int(11)","Null":"YES","Key":"MUL","Default":null,"Extra":""},{"Field":"order","Type":"int(11)","Null":"YES","Key":"","Default":null,"Extra":""}]
 * DMT 2017
 * GENERATED: 5 / 8 / 2017 - 14:44:43
 **/
var BaseModel = require('../utils/model.js')
var util = require('util')
var Form_question = function () {
	var params = [{
		table:'form_question',
		fields :[{"Field":"id_form","Type":"int(11)","Null":"YES","Key":"MUL","Default":null,"Extra":""},{"Field":"id_question","Type":"int(11)","Null":"YES","Key":"MUL","Default":null,"Extra":""},{"Field":"order","Type":"int(11)","Null":"YES","Key":"","Default":null,"Extra":""}],
		model:'mysql'
	}]
	BaseModel.apply(this, params)
	return this
};
util.inherits(Form_question, BaseModel)
module.exports = Form_question