/**  * MODEL AUTO_GENERATED BY DMT-GENERATOR
 * institution
 * [{"Field":"id","Type":"int(11)","Null":"NO","Key":"PRI","Default":null,"Extra":"auto_increment"},{"Field":"name","Type":"varchar(255)","Null":"YES","Key":"","Default":null,"Extra":""},{"Field":"id_city","Type":"int(11)","Null":"YES","Key":"MUL","Default":null,"Extra":""},{"Field":"id_user_creator","Type":"int(11)","Null":"YES","Key":"MUL","Default":null,"Extra":""},{"Field":"address","Type":"varchar(255)","Null":"YES","Key":"","Default":null,"Extra":""},{"Field":"email","Type":"varchar(255)","Null":"YES","Key":"","Default":null,"Extra":""},{"Field":"second_email","Type":"varchar(255)","Null":"YES","Key":"","Default":null,"Extra":""},{"Field":"phone","Type":"varchar(255)","Null":"YES","Key":"","Default":null,"Extra":""},{"Field":"head_sector","Type":"tinyint(1)","Null":"YES","Key":"","Default":null,"Extra":""},{"Field":"timestamp","Type":"timestamp","Null":"NO","Key":"","Default":"CURRENT_TIMESTAMP","Extra":""}]
 * DMT 2017
 * GENERATED: 28 / 1 / 2017 - 17:36:25
 **/
var BaseModel = require('../utils/model.js')
var util = require('util')
var Institution = function () {
	this.fields = [{"Field":"id","Type":"int(11)","Null":"NO","Key":"PRI","Default":null,"Extra":"auto_increment"},{"Field":"name","Type":"varchar(255)","Null":"YES","Key":"","Default":null,"Extra":""},{"Field":"id_city","Type":"int(11)","Null":"YES","Key":"MUL","Default":null,"Extra":""},{"Field":"id_user_creator","Type":"int(11)","Null":"YES","Key":"MUL","Default":null,"Extra":""},{"Field":"address","Type":"varchar(255)","Null":"YES","Key":"","Default":null,"Extra":""},{"Field":"email","Type":"varchar(255)","Null":"YES","Key":"","Default":null,"Extra":""},{"Field":"second_email","Type":"varchar(255)","Null":"YES","Key":"","Default":null,"Extra":""},{"Field":"phone","Type":"varchar(255)","Null":"YES","Key":"","Default":null,"Extra":""},{"Field":"head_sector","Type":"tinyint(1)","Null":"YES","Key":"","Default":null,"Extra":""},{"Field":"timestamp","Type":"timestamp","Null":"NO","Key":"","Default":"CURRENT_TIMESTAMP","Extra":""}]
	var params = ['institution', 'mysql']
	BaseModel.apply(this, params)
	return this
};
util.inherits(Institution, BaseModel)
module.exports = Institution