/**  * MODEL AUTO_GENERATED BY DMT-GENERATOR
 * media
 * [{"Field":"id","Type":"int(11)","Null":"NO","Key":"PRI","Default":null,"Extra":"auto_increment"},{"Field":"url","Type":"varchar(50)","Null":"YES","Key":"","Default":null,"Extra":""},{"Field":"type","Type":"tinyint(4)","Null":"YES","Key":"","Default":null,"Extra":""},{"Field":"timestamp","Type":"timestamp","Null":"NO","Key":"","Default":"CURRENT_TIMESTAMP","Extra":""}]
 * DMT 2017
 * GENERATED: 28 / 1 / 2017 - 14:36:28
 **/
var BaseModel = require('../utils/model.js')
var util = require('util')
var Media = function () {
	this.fields = [{"Field":"id","Type":"int(11)","Null":"NO","Key":"PRI","Default":null,"Extra":"auto_increment"},{"Field":"url","Type":"varchar(50)","Null":"YES","Key":"","Default":null,"Extra":""},{"Field":"type","Type":"tinyint(4)","Null":"YES","Key":"","Default":null,"Extra":""},{"Field":"timestamp","Type":"timestamp","Null":"NO","Key":"","Default":"CURRENT_TIMESTAMP","Extra":""}]
	var params = ['media', 'mysql']
	BaseModel.apply(this, params)
	return this
};
util.inherits(Media, BaseModel)
module.exports = Media