/**  * MODEL AUTO_GENERATED BY DMT-GENERATOR
 * message
 * [{"Field":"id","Type":"int(11)","Null":"NO","Key":"PRI","Default":null,"Extra":"auto_increment"},{"Field":"text","Type":"text","Null":"YES","Key":"","Default":null,"Extra":""},{"Field":"id_topic","Type":"int(11)","Null":"YES","Key":"MUL","Default":null,"Extra":""},{"Field":"id_user","Type":"int(11)","Null":"YES","Key":"MUL","Default":null,"Extra":""},{"Field":"timestamp","Type":"timestamp","Null":"NO","Key":"","Default":"CURRENT_TIMESTAMP","Extra":""}]
 * DMT 2017
 * GENERATED: 2 / 2 / 2017 - 21:17:48
 **/
var BaseModel = require('../utils/model.js')
var util = require('util')
var Message = function () {
	this.fields = [
		{"Field":"id","Type":"int(11)","Null":"NO","Key":"PRI","Default":null,"Extra":"auto_increment"},
		{"Field":"text","Type":"text","Null":"YES","Key":"","Default":null,"Extra":""},
		{"Field":"id_topic","Type":"int(11)","Null":"YES","Key":"MUL","Default":null,"Extra":""},
		{"Field":"id_user","Type":"int(11)","Null":"YES","Key":"MUL","Default":null,"Extra":""},
		{"Field":"timestamp","Type":"timestamp","Null":"NO","Key":"","Default":"CURRENT_TIMESTAMP","Extra":""}]
	var params = ['message', 'mysql']
	BaseModel.apply(this, params)
	return this
}
util.inherits(Message, BaseModel)
module.exports = Message