/**  * MODEL AUTO_GENERATED BY DMT-GENERATOR
 * paises
 * [{"Field":"id","Type":"int(11)","Null":"YES","Key":"","Default":null,"Extra":""},{"Field":"name","Type":"text","Null":"YES","Key":"","Default":null,"Extra":""}]
 * DMT 2017
 * GENERATED: 24 / 8 / 2017 - 18:2:54
 **/
var BaseModel = require('../utils/model.js')
var util = require('util')
var Paises = function () {
	var params = [{
		table:'paises',
		fields :[{"Field":"id","Type":"int(11)","Null":"YES","Key":"","Default":null,"Extra":""},{"Field":"name","Type":"text","Null":"YES","Key":"","Default":null,"Extra":""}],
		model:'mysql'
	}]
	BaseModel.apply(this, params)
	return this
};
util.inherits(Paises, BaseModel)
module.exports = Paises