/**  * MODEL AUTO_GENERATED BY DMT-GENERATOR
 * question
 * [{"Field":"id","Type":"int(11)","Null":"NO","Key":"PRI","Default":null,"Extra":"auto_increment"},{"Field":"text","Type":"text","Null":"YES","Key":"","Default":null,"Extra":""},{"Field":"id_type","Type":"int(11)","Null":"YES","Key":"MUL","Default":null,"Extra":""},{"Field":"id_topic","Type":"int(11)","Null":"YES","Key":"MUL","Default":null,"Extra":""}]
 * DMT 2017
 * GENERATED: 6 / 2 / 2017 - 11:59:19
 **/
var BaseModel = require('../utils/model.js')
var util = require('util')
var Question = function () {
	this.fields = [{"Field":"id","Type":"int(11)","Null":"NO","Key":"PRI","Default":null,"Extra":"auto_increment"},{"Field":"text","Type":"text","Null":"YES","Key":"","Default":null,"Extra":""},{"Field":"id_type","Type":"int(11)","Null":"YES","Key":"MUL","Default":null,"Extra":""},{"Field":"id_topic","Type":"int(11)","Null":"YES","Key":"MUL","Default":null,"Extra":""}]
	var params = ['question', 'mysql']
	BaseModel.apply(this, params)
	return this
};
util.inherits(Question, BaseModel)
module.exports = Question