/**  * MODEL AUTO_GENERATED BY DMT-GENERATOR
 * user_role
 * [{"Field":"id_user","Type":"int(11)","Null":"YES","Key":"MUL","Default":null,"Extra":""},{"Field":"id_role","Type":"int(11)","Null":"YES","Key":"MUL","Default":null,"Extra":""}]
 * DMT 2017
 * GENERATED: 19 / 1 / 2017 - 0:59:49
 **/
var BaseModel = require('../utils/model.js')
var util = require('util')
var User_role = function () {
	this.fields = [{"Field":"id_user","Type":"int(11)","Null":"YES","Key":"MUL","Default":null,"Extra":""},{"Field":"id_role","Type":"int(11)","Null":"YES","Key":"MUL","Default":null,"Extra":""}]
	var params = ['user_role', 'mysql']
	BaseModel.apply(this, params)
	return this
};
util.inherits(User_role, BaseModel)
module.exports = User_role